package com.school.repertory.dao.mapper;

import com.school.repertory.controller.form.SearchInventoryForm;
import com.school.repertory.dao.model.GoodsAndStorageModel;
import com.school.repertory.dao.model.GoodsStorage;
import com.school.repertory.dao.model.GoodsStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsStorageSqlProvider.class, method="countByExample")
    long countByExample(GoodsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsStorageSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @Delete({
        "delete from goods_storage",
        "where storage_goods_no = #{storageGoodsNo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String storageGoodsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @Insert({
        "insert into goods_storage (storage_goods_no, storage_count)",
        "values (#{storageGoodsNo,jdbcType=VARCHAR}, #{storageCount,jdbcType=INTEGER})"
    })
    int insert(GoodsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsStorageSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsStorageSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="storage_goods_no", property="storageGoodsNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="storage_count", property="storageCount", jdbcType=JdbcType.INTEGER)
    })
    List<GoodsStorage> selectByExample(GoodsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "storage_goods_no, storage_count",
        "from goods_storage",
        "where storage_goods_no = #{storageGoodsNo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="storage_goods_no", property="storageGoodsNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="storage_count", property="storageCount", jdbcType=JdbcType.INTEGER)
    })
    GoodsStorage selectByPrimaryKey(String storageGoodsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsStorageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsStorage record, @Param("example") GoodsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsStorageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsStorage record, @Param("example") GoodsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsStorageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_storage
     *
     * @mbg.generated
     */
    @Update({
        "update goods_storage",
        "set storage_count = #{storageCount,jdbcType=INTEGER}",
        "where storage_goods_no = #{storageGoodsNo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsStorage record);
    
    @SelectProvider(type=GoodsStorageSqlProvider.class, method="selectGoodsAndStorage")
    @Results({
    	@Result(column="goods_no", property="goodsNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="goods_name", property="goodsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_size_length", property="goodsSizeLength", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_size_width", property="goodsSizeWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_size_height", property="goodsSizeHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_value", property="goodsValue", jdbcType=JdbcType.DECIMAL),
        @Result(column="storage_count", property="storageCount", jdbcType=JdbcType.INTEGER)
    })
    List<GoodsAndStorageModel> selectGoodsAndStorage(SearchInventoryForm form);
}