package com.school.repertory.dao.mapper;

import com.school.repertory.dao.model.InRecord;
import com.school.repertory.dao.model.InRecordExample.Criteria;
import com.school.repertory.dao.model.InRecordExample.Criterion;
import com.school.repertory.dao.model.InRecordExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class InRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String countByExample(InRecordExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("in_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String deleteByExample(InRecordExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("in_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String insertSelective(InRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("in_record");
        
        if (record.getInRecordId() != null) {
            sql.VALUES("in_record_id", "#{inRecordId,jdbcType=INTEGER}");
        }
        
        if (record.getInRecordSupplierNo() != null) {
            sql.VALUES("in_record_supplier_no", "#{inRecordSupplierNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordGoodsNo() != null) {
            sql.VALUES("in_record_goods_no", "#{inRecordGoodsNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordCount() != null) {
            sql.VALUES("in_record_count", "#{inRecordCount,jdbcType=INTEGER}");
        }
        
        if (record.getInRecordDt() != null) {
            sql.VALUES("in_record_dt", "#{inRecordDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInRecordPersonNo() != null) {
            sql.VALUES("in_record_person_no", "#{inRecordPersonNo,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String selectByExample(InRecordExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("in_record_id");
        } else {
            sql.SELECT("in_record_id");
        }
        sql.SELECT("in_record_supplier_no");
        sql.SELECT("in_record_goods_no");
        sql.SELECT("in_record_count");
        sql.SELECT("in_record_dt");
        sql.SELECT("in_record_person_no");
        sql.FROM("in_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        InRecord record = (InRecord) parameter.get("record");
        InRecordExample example = (InRecordExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("in_record");
        
        if (record.getInRecordId() != null) {
            sql.SET("in_record_id = #{record.inRecordId,jdbcType=INTEGER}");
        }
        
        if (record.getInRecordSupplierNo() != null) {
            sql.SET("in_record_supplier_no = #{record.inRecordSupplierNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordGoodsNo() != null) {
            sql.SET("in_record_goods_no = #{record.inRecordGoodsNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordCount() != null) {
            sql.SET("in_record_count = #{record.inRecordCount,jdbcType=INTEGER}");
        }
        
        if (record.getInRecordDt() != null) {
            sql.SET("in_record_dt = #{record.inRecordDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInRecordPersonNo() != null) {
            sql.SET("in_record_person_no = #{record.inRecordPersonNo,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("in_record");
        
        sql.SET("in_record_id = #{record.inRecordId,jdbcType=INTEGER}");
        sql.SET("in_record_supplier_no = #{record.inRecordSupplierNo,jdbcType=VARCHAR}");
        sql.SET("in_record_goods_no = #{record.inRecordGoodsNo,jdbcType=VARCHAR}");
        sql.SET("in_record_count = #{record.inRecordCount,jdbcType=INTEGER}");
        sql.SET("in_record_dt = #{record.inRecordDt,jdbcType=TIMESTAMP}");
        sql.SET("in_record_person_no = #{record.inRecordPersonNo,jdbcType=VARCHAR}");
        
        InRecordExample example = (InRecordExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(InRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("in_record");
        
        if (record.getInRecordSupplierNo() != null) {
            sql.SET("in_record_supplier_no = #{inRecordSupplierNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordGoodsNo() != null) {
            sql.SET("in_record_goods_no = #{inRecordGoodsNo,jdbcType=VARCHAR}");
        }
        
        if (record.getInRecordCount() != null) {
            sql.SET("in_record_count = #{inRecordCount,jdbcType=INTEGER}");
        }
        
        if (record.getInRecordDt() != null) {
            sql.SET("in_record_dt = #{inRecordDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInRecordPersonNo() != null) {
            sql.SET("in_record_person_no = #{inRecordPersonNo,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("in_record_id = #{inRecordId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, InRecordExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}