package com.school.repertory.dao.mapper;

import com.school.repertory.dao.model.Supplier;
import com.school.repertory.dao.model.SupplierExample.Criteria;
import com.school.repertory.dao.model.SupplierExample.Criterion;
import com.school.repertory.dao.model.SupplierExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class SupplierSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String countByExample(SupplierExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("supplier");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String deleteByExample(SupplierExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("supplier");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String insertSelective(Supplier record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("supplier");
        
        if (record.getSupplierNo() != null) {
            sql.VALUES("supplier_no", "#{supplierNo,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierName() != null) {
            sql.VALUES("supplier_name", "#{supplierName,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierPerson() != null) {
            sql.VALUES("supplier_person", "#{supplierPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierTelephone() != null) {
            sql.VALUES("supplier_telephone", "#{supplierTelephone,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierEmail() != null) {
            sql.VALUES("supplier_email", "#{supplierEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierAddress() != null) {
            sql.VALUES("supplier_address", "#{supplierAddress,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String selectByExample(SupplierExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("supplier_no");
        } else {
            sql.SELECT("supplier_no");
        }
        sql.SELECT("supplier_name");
        sql.SELECT("supplier_person");
        sql.SELECT("supplier_telephone");
        sql.SELECT("supplier_email");
        sql.SELECT("supplier_address");
        sql.FROM("supplier");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Supplier record = (Supplier) parameter.get("record");
        SupplierExample example = (SupplierExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("supplier");
        
        if (record.getSupplierNo() != null) {
            sql.SET("supplier_no = #{record.supplierNo,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierName() != null) {
            sql.SET("supplier_name = #{record.supplierName,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierPerson() != null) {
            sql.SET("supplier_person = #{record.supplierPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierTelephone() != null) {
            sql.SET("supplier_telephone = #{record.supplierTelephone,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierEmail() != null) {
            sql.SET("supplier_email = #{record.supplierEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierAddress() != null) {
            sql.SET("supplier_address = #{record.supplierAddress,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("supplier");
        
        sql.SET("supplier_no = #{record.supplierNo,jdbcType=VARCHAR}");
        sql.SET("supplier_name = #{record.supplierName,jdbcType=VARCHAR}");
        sql.SET("supplier_person = #{record.supplierPerson,jdbcType=VARCHAR}");
        sql.SET("supplier_telephone = #{record.supplierTelephone,jdbcType=VARCHAR}");
        sql.SET("supplier_email = #{record.supplierEmail,jdbcType=VARCHAR}");
        sql.SET("supplier_address = #{record.supplierAddress,jdbcType=VARCHAR}");
        
        SupplierExample example = (SupplierExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Supplier record) {
        SQL sql = new SQL();
        sql.UPDATE("supplier");
        
        if (record.getSupplierName() != null) {
            sql.SET("supplier_name = #{supplierName,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierPerson() != null) {
            sql.SET("supplier_person = #{supplierPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierTelephone() != null) {
            sql.SET("supplier_telephone = #{supplierTelephone,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierEmail() != null) {
            sql.SET("supplier_email = #{supplierEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getSupplierAddress() != null) {
            sql.SET("supplier_address = #{supplierAddress,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("supplier_no = #{supplierNo,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, SupplierExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}