package com.school.repertory.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer
 */
public class Customer {
    /**
     * Database Column Remarks:
     *   客户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_no
     *
     * @mbg.generated
     */
    private String customerNo;

    /**
     * Database Column Remarks:
     *   客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   客户代表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_person
     *
     * @mbg.generated
     */
    private String customerPerson;

    /**
     * Database Column Remarks:
     *   客户电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_telephone
     *
     * @mbg.generated
     */
    private String customerTelephone;

    /**
     * Database Column Remarks:
     *   客户邮件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_email
     *
     * @mbg.generated
     */
    private String customerEmail;

    /**
     * Database Column Remarks:
     *   客户地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_address
     *
     * @mbg.generated
     */
    private String customerAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_no
     *
     * @return the value of customer.customer_no
     *
     * @mbg.generated
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_no
     *
     * @param customerNo the value for customer.customer_no
     *
     * @mbg.generated
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo == null ? null : customerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_person
     *
     * @return the value of customer.customer_person
     *
     * @mbg.generated
     */
    public String getCustomerPerson() {
        return customerPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_person
     *
     * @param customerPerson the value for customer.customer_person
     *
     * @mbg.generated
     */
    public void setCustomerPerson(String customerPerson) {
        this.customerPerson = customerPerson == null ? null : customerPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_telephone
     *
     * @return the value of customer.customer_telephone
     *
     * @mbg.generated
     */
    public String getCustomerTelephone() {
        return customerTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_telephone
     *
     * @param customerTelephone the value for customer.customer_telephone
     *
     * @mbg.generated
     */
    public void setCustomerTelephone(String customerTelephone) {
        this.customerTelephone = customerTelephone == null ? null : customerTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_email
     *
     * @return the value of customer.customer_email
     *
     * @mbg.generated
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_email
     *
     * @param customerEmail the value for customer.customer_email
     *
     * @mbg.generated
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_address
     *
     * @return the value of customer.customer_address
     *
     * @mbg.generated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_address
     *
     * @param customerAddress the value for customer.customer_address
     *
     * @mbg.generated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }
}