package com.school.repertory.dao.model;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table in_record
 */
public class InRecord {
    /**
     * Database Column Remarks:
     *   入库记录id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_id
     *
     * @mbg.generated
     */
    private Integer inRecordId;

    /**
     * Database Column Remarks:
     *   供应商编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_supplier_no
     *
     * @mbg.generated
     */
    private String inRecordSupplierNo;

    /**
     * Database Column Remarks:
     *   货物编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_goods_no
     *
     * @mbg.generated
     */
    private String inRecordGoodsNo;

    /**
     * Database Column Remarks:
     *   入库数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_count
     *
     * @mbg.generated
     */
    private Integer inRecordCount;

    /**
     * Database Column Remarks:
     *   入库时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_dt
     *
     * @mbg.generated
     */
    private LocalDateTime inRecordDt;

    /**
     * Database Column Remarks:
     *   入库经手人编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_record.in_record_person_no
     *
     * @mbg.generated
     */
    private String inRecordPersonNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_id
     *
     * @return the value of in_record.in_record_id
     *
     * @mbg.generated
     */
    public Integer getInRecordId() {
        return inRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_id
     *
     * @param inRecordId the value for in_record.in_record_id
     *
     * @mbg.generated
     */
    public void setInRecordId(Integer inRecordId) {
        this.inRecordId = inRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_supplier_no
     *
     * @return the value of in_record.in_record_supplier_no
     *
     * @mbg.generated
     */
    public String getInRecordSupplierNo() {
        return inRecordSupplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_supplier_no
     *
     * @param inRecordSupplierNo the value for in_record.in_record_supplier_no
     *
     * @mbg.generated
     */
    public void setInRecordSupplierNo(String inRecordSupplierNo) {
        this.inRecordSupplierNo = inRecordSupplierNo == null ? null : inRecordSupplierNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_goods_no
     *
     * @return the value of in_record.in_record_goods_no
     *
     * @mbg.generated
     */
    public String getInRecordGoodsNo() {
        return inRecordGoodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_goods_no
     *
     * @param inRecordGoodsNo the value for in_record.in_record_goods_no
     *
     * @mbg.generated
     */
    public void setInRecordGoodsNo(String inRecordGoodsNo) {
        this.inRecordGoodsNo = inRecordGoodsNo == null ? null : inRecordGoodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_count
     *
     * @return the value of in_record.in_record_count
     *
     * @mbg.generated
     */
    public Integer getInRecordCount() {
        return inRecordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_count
     *
     * @param inRecordCount the value for in_record.in_record_count
     *
     * @mbg.generated
     */
    public void setInRecordCount(Integer inRecordCount) {
        this.inRecordCount = inRecordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_dt
     *
     * @return the value of in_record.in_record_dt
     *
     * @mbg.generated
     */
    public LocalDateTime getInRecordDt() {
        return inRecordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_dt
     *
     * @param inRecordDt the value for in_record.in_record_dt
     *
     * @mbg.generated
     */
    public void setInRecordDt(LocalDateTime inRecordDt) {
        this.inRecordDt = inRecordDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_record.in_record_person_no
     *
     * @return the value of in_record.in_record_person_no
     *
     * @mbg.generated
     */
    public String getInRecordPersonNo() {
        return inRecordPersonNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_record.in_record_person_no
     *
     * @param inRecordPersonNo the value for in_record.in_record_person_no
     *
     * @mbg.generated
     */
    public void setInRecordPersonNo(String inRecordPersonNo) {
        this.inRecordPersonNo = inRecordPersonNo == null ? null : inRecordPersonNo.trim();
    }
}