package com.school.repertory.dao.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class InRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public InRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInRecordIdIsNull() {
            addCriterion("in_record_id is null");
            return (Criteria) this;
        }

        public Criteria andInRecordIdIsNotNull() {
            addCriterion("in_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordIdEqualTo(Integer value) {
            addCriterion("in_record_id =", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdNotEqualTo(Integer value) {
            addCriterion("in_record_id <>", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdGreaterThan(Integer value) {
            addCriterion("in_record_id >", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_record_id >=", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdLessThan(Integer value) {
            addCriterion("in_record_id <", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("in_record_id <=", value, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdIn(List<Integer> values) {
            addCriterion("in_record_id in", values, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdNotIn(List<Integer> values) {
            addCriterion("in_record_id not in", values, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("in_record_id between", value1, value2, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("in_record_id not between", value1, value2, "inRecordId");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoIsNull() {
            addCriterion("in_record_supplier_no is null");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoIsNotNull() {
            addCriterion("in_record_supplier_no is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoEqualTo(String value) {
            addCriterion("in_record_supplier_no =", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoNotEqualTo(String value) {
            addCriterion("in_record_supplier_no <>", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoGreaterThan(String value) {
            addCriterion("in_record_supplier_no >", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoGreaterThanOrEqualTo(String value) {
            addCriterion("in_record_supplier_no >=", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoLessThan(String value) {
            addCriterion("in_record_supplier_no <", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoLessThanOrEqualTo(String value) {
            addCriterion("in_record_supplier_no <=", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoLike(String value) {
            addCriterion("in_record_supplier_no like", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoNotLike(String value) {
            addCriterion("in_record_supplier_no not like", value, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoIn(List<String> values) {
            addCriterion("in_record_supplier_no in", values, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoNotIn(List<String> values) {
            addCriterion("in_record_supplier_no not in", values, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoBetween(String value1, String value2) {
            addCriterion("in_record_supplier_no between", value1, value2, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordSupplierNoNotBetween(String value1, String value2) {
            addCriterion("in_record_supplier_no not between", value1, value2, "inRecordSupplierNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoIsNull() {
            addCriterion("in_record_goods_no is null");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoIsNotNull() {
            addCriterion("in_record_goods_no is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoEqualTo(String value) {
            addCriterion("in_record_goods_no =", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoNotEqualTo(String value) {
            addCriterion("in_record_goods_no <>", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoGreaterThan(String value) {
            addCriterion("in_record_goods_no >", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoGreaterThanOrEqualTo(String value) {
            addCriterion("in_record_goods_no >=", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoLessThan(String value) {
            addCriterion("in_record_goods_no <", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoLessThanOrEqualTo(String value) {
            addCriterion("in_record_goods_no <=", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoLike(String value) {
            addCriterion("in_record_goods_no like", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoNotLike(String value) {
            addCriterion("in_record_goods_no not like", value, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoIn(List<String> values) {
            addCriterion("in_record_goods_no in", values, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoNotIn(List<String> values) {
            addCriterion("in_record_goods_no not in", values, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoBetween(String value1, String value2) {
            addCriterion("in_record_goods_no between", value1, value2, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordGoodsNoNotBetween(String value1, String value2) {
            addCriterion("in_record_goods_no not between", value1, value2, "inRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andInRecordCountIsNull() {
            addCriterion("in_record_count is null");
            return (Criteria) this;
        }

        public Criteria andInRecordCountIsNotNull() {
            addCriterion("in_record_count is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordCountEqualTo(Integer value) {
            addCriterion("in_record_count =", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountNotEqualTo(Integer value) {
            addCriterion("in_record_count <>", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountGreaterThan(Integer value) {
            addCriterion("in_record_count >", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_record_count >=", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountLessThan(Integer value) {
            addCriterion("in_record_count <", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountLessThanOrEqualTo(Integer value) {
            addCriterion("in_record_count <=", value, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountIn(List<Integer> values) {
            addCriterion("in_record_count in", values, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountNotIn(List<Integer> values) {
            addCriterion("in_record_count not in", values, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountBetween(Integer value1, Integer value2) {
            addCriterion("in_record_count between", value1, value2, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordCountNotBetween(Integer value1, Integer value2) {
            addCriterion("in_record_count not between", value1, value2, "inRecordCount");
            return (Criteria) this;
        }

        public Criteria andInRecordDtIsNull() {
            addCriterion("in_record_dt is null");
            return (Criteria) this;
        }

        public Criteria andInRecordDtIsNotNull() {
            addCriterion("in_record_dt is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordDtEqualTo(LocalDateTime value) {
            addCriterion("in_record_dt =", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtNotEqualTo(LocalDateTime value) {
            addCriterion("in_record_dt <>", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtGreaterThan(LocalDateTime value) {
            addCriterion("in_record_dt >", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("in_record_dt >=", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtLessThan(LocalDateTime value) {
            addCriterion("in_record_dt <", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("in_record_dt <=", value, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtIn(List<LocalDateTime> values) {
            addCriterion("in_record_dt in", values, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtNotIn(List<LocalDateTime> values) {
            addCriterion("in_record_dt not in", values, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("in_record_dt between", value1, value2, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordDtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("in_record_dt not between", value1, value2, "inRecordDt");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoIsNull() {
            addCriterion("in_record_person_no is null");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoIsNotNull() {
            addCriterion("in_record_person_no is not null");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoEqualTo(String value) {
            addCriterion("in_record_person_no =", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoNotEqualTo(String value) {
            addCriterion("in_record_person_no <>", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoGreaterThan(String value) {
            addCriterion("in_record_person_no >", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoGreaterThanOrEqualTo(String value) {
            addCriterion("in_record_person_no >=", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoLessThan(String value) {
            addCriterion("in_record_person_no <", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoLessThanOrEqualTo(String value) {
            addCriterion("in_record_person_no <=", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoLike(String value) {
            addCriterion("in_record_person_no like", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoNotLike(String value) {
            addCriterion("in_record_person_no not like", value, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoIn(List<String> values) {
            addCriterion("in_record_person_no in", values, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoNotIn(List<String> values) {
            addCriterion("in_record_person_no not in", values, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoBetween(String value1, String value2) {
            addCriterion("in_record_person_no between", value1, value2, "inRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andInRecordPersonNoNotBetween(String value1, String value2) {
            addCriterion("in_record_person_no not between", value1, value2, "inRecordPersonNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}