package com.school.repertory.dao.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class OutRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public OutRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table out_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOutRecordIdIsNull() {
            addCriterion("out_record_id is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdIsNotNull() {
            addCriterion("out_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdEqualTo(Integer value) {
            addCriterion("out_record_id =", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdNotEqualTo(Integer value) {
            addCriterion("out_record_id <>", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdGreaterThan(Integer value) {
            addCriterion("out_record_id >", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("out_record_id >=", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdLessThan(Integer value) {
            addCriterion("out_record_id <", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("out_record_id <=", value, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdIn(List<Integer> values) {
            addCriterion("out_record_id in", values, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdNotIn(List<Integer> values) {
            addCriterion("out_record_id not in", values, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("out_record_id between", value1, value2, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("out_record_id not between", value1, value2, "outRecordId");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoIsNull() {
            addCriterion("out_record_customer_no is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoIsNotNull() {
            addCriterion("out_record_customer_no is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoEqualTo(String value) {
            addCriterion("out_record_customer_no =", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoNotEqualTo(String value) {
            addCriterion("out_record_customer_no <>", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoGreaterThan(String value) {
            addCriterion("out_record_customer_no >", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_record_customer_no >=", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoLessThan(String value) {
            addCriterion("out_record_customer_no <", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoLessThanOrEqualTo(String value) {
            addCriterion("out_record_customer_no <=", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoLike(String value) {
            addCriterion("out_record_customer_no like", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoNotLike(String value) {
            addCriterion("out_record_customer_no not like", value, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoIn(List<String> values) {
            addCriterion("out_record_customer_no in", values, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoNotIn(List<String> values) {
            addCriterion("out_record_customer_no not in", values, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoBetween(String value1, String value2) {
            addCriterion("out_record_customer_no between", value1, value2, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCustomerNoNotBetween(String value1, String value2) {
            addCriterion("out_record_customer_no not between", value1, value2, "outRecordCustomerNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoIsNull() {
            addCriterion("out_record_goods_no is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoIsNotNull() {
            addCriterion("out_record_goods_no is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoEqualTo(String value) {
            addCriterion("out_record_goods_no =", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoNotEqualTo(String value) {
            addCriterion("out_record_goods_no <>", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoGreaterThan(String value) {
            addCriterion("out_record_goods_no >", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_record_goods_no >=", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoLessThan(String value) {
            addCriterion("out_record_goods_no <", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoLessThanOrEqualTo(String value) {
            addCriterion("out_record_goods_no <=", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoLike(String value) {
            addCriterion("out_record_goods_no like", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoNotLike(String value) {
            addCriterion("out_record_goods_no not like", value, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoIn(List<String> values) {
            addCriterion("out_record_goods_no in", values, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoNotIn(List<String> values) {
            addCriterion("out_record_goods_no not in", values, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoBetween(String value1, String value2) {
            addCriterion("out_record_goods_no between", value1, value2, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordGoodsNoNotBetween(String value1, String value2) {
            addCriterion("out_record_goods_no not between", value1, value2, "outRecordGoodsNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountIsNull() {
            addCriterion("out_record_count is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountIsNotNull() {
            addCriterion("out_record_count is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountEqualTo(Integer value) {
            addCriterion("out_record_count =", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountNotEqualTo(Integer value) {
            addCriterion("out_record_count <>", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountGreaterThan(Integer value) {
            addCriterion("out_record_count >", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("out_record_count >=", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountLessThan(Integer value) {
            addCriterion("out_record_count <", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountLessThanOrEqualTo(Integer value) {
            addCriterion("out_record_count <=", value, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountIn(List<Integer> values) {
            addCriterion("out_record_count in", values, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountNotIn(List<Integer> values) {
            addCriterion("out_record_count not in", values, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountBetween(Integer value1, Integer value2) {
            addCriterion("out_record_count between", value1, value2, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordCountNotBetween(Integer value1, Integer value2) {
            addCriterion("out_record_count not between", value1, value2, "outRecordCount");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtIsNull() {
            addCriterion("out_record_dt is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtIsNotNull() {
            addCriterion("out_record_dt is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtEqualTo(LocalDateTime value) {
            addCriterion("out_record_dt =", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtNotEqualTo(LocalDateTime value) {
            addCriterion("out_record_dt <>", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtGreaterThan(LocalDateTime value) {
            addCriterion("out_record_dt >", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("out_record_dt >=", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtLessThan(LocalDateTime value) {
            addCriterion("out_record_dt <", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("out_record_dt <=", value, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtIn(List<LocalDateTime> values) {
            addCriterion("out_record_dt in", values, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtNotIn(List<LocalDateTime> values) {
            addCriterion("out_record_dt not in", values, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("out_record_dt between", value1, value2, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordDtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("out_record_dt not between", value1, value2, "outRecordDt");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoIsNull() {
            addCriterion("out_record_person_no is null");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoIsNotNull() {
            addCriterion("out_record_person_no is not null");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoEqualTo(String value) {
            addCriterion("out_record_person_no =", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoNotEqualTo(String value) {
            addCriterion("out_record_person_no <>", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoGreaterThan(String value) {
            addCriterion("out_record_person_no >", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_record_person_no >=", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoLessThan(String value) {
            addCriterion("out_record_person_no <", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoLessThanOrEqualTo(String value) {
            addCriterion("out_record_person_no <=", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoLike(String value) {
            addCriterion("out_record_person_no like", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoNotLike(String value) {
            addCriterion("out_record_person_no not like", value, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoIn(List<String> values) {
            addCriterion("out_record_person_no in", values, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoNotIn(List<String> values) {
            addCriterion("out_record_person_no not in", values, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoBetween(String value1, String value2) {
            addCriterion("out_record_person_no between", value1, value2, "outRecordPersonNo");
            return (Criteria) this;
        }

        public Criteria andOutRecordPersonNoNotBetween(String value1, String value2) {
            addCriterion("out_record_person_no not between", value1, value2, "outRecordPersonNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table out_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table out_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}