package com.school.repertory.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table system_user
 */
public class SystemUser {
    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_username
     *
     * @mbg.generated
     */
    private String userUsername;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     * Database Column Remarks:
     *   用户全名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_fullname
     *
     * @mbg.generated
     */
    private String userFullname;

    /**
     * Database Column Remarks:
     *   用户性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_sex
     *
     * @mbg.generated
     */
    private String userSex;

    /**
     * Database Column Remarks:
     *   用户电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     * Database Column Remarks:
     *   用户地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     * Database Column Remarks:
     *   是否为超级管理员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_is_super_admin
     *
     * @mbg.generated
     */
    private Boolean userIsSuperAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_username
     *
     * @return the value of system_user.user_username
     *
     * @mbg.generated
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_username
     *
     * @param userUsername the value for system_user.user_username
     *
     * @mbg.generated
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername == null ? null : userUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_password
     *
     * @return the value of system_user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_password
     *
     * @param userPassword the value for system_user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_fullname
     *
     * @return the value of system_user.user_fullname
     *
     * @mbg.generated
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_fullname
     *
     * @param userFullname the value for system_user.user_fullname
     *
     * @mbg.generated
     */
    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname == null ? null : userFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_sex
     *
     * @return the value of system_user.user_sex
     *
     * @mbg.generated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_sex
     *
     * @param userSex the value for system_user.user_sex
     *
     * @mbg.generated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_phone
     *
     * @return the value of system_user.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_phone
     *
     * @param userPhone the value for system_user.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_address
     *
     * @return the value of system_user.user_address
     *
     * @mbg.generated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_address
     *
     * @param userAddress the value for system_user.user_address
     *
     * @mbg.generated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_is_super_admin
     *
     * @return the value of system_user.user_is_super_admin
     *
     * @mbg.generated
     */
    public Boolean getUserIsSuperAdmin() {
        return userIsSuperAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_is_super_admin
     *
     * @param userIsSuperAdmin the value for system_user.user_is_super_admin
     *
     * @mbg.generated
     */
    public void setUserIsSuperAdmin(Boolean userIsSuperAdmin) {
        this.userIsSuperAdmin = userIsSuperAdmin;
    }
}